import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import os

# --- 1. SETTINGS & BRANDING ---
# Official College of the Ozarks Branding
logo_path = "cofo-logo.jpg"

try:
    favicon = Image.open(logo_path)
    st.set_page_config(
        page_title="CofO | Wave Optics Lab", 
        page_icon=favicon, 
        layout="centered"
    )
except:
    st.set_page_config(
        page_title="CofO | Wave Optics Lab", 
        layout="centered"
    )

st.markdown("""
    <style>
        /* Target EVERYTHING inside the Sidebar and force it to White */
        section[data-testid="stSidebar"] * {
            color: white !important;
        }
        
        /* Fix the Input Boxes in the Sidebar so they are readable */
        section[data-testid="stSidebar"] input {
            color: #8D203C !important; 
        }

        /* Ensure the Main Area stays Black */
        .stApp p, .stApp h1, .stApp h2, .stApp h3, .stApp span {
            color: #000000;
        }
        
        /* Keep the Metric Labels Black */
        [data-testid="stMetricLabel"] {
            color: #444444 !important;
        }
        [data-testid="stMetricValue"] {
            color: #000000 !important;
        }

        /* Make the Sidebar Divider visible but subtle */
        section[data-testid="stSidebar"] hr {
            border-top: 1px solid #ffffff44 !important;
        }
    </style>
""", unsafe_allow_html=True)

if os.path.exists(logo_path):
    logo = Image.open(logo_path)
    st.sidebar.image(logo, use_container_width=True)
else:
    st.sidebar.warning(f"Logo '{logo_path}' not found in repo.")

# Sidebar Branding
st.sidebar.markdown("### **College of the Ozarks**\nDepartment of Mathematics and Physics")
st.sidebar.divider()

# --- Styled Main Header with Logo ---
col1, col2 = st.columns([1, 4]) 

with col1:
    if os.path.exists(logo_path):
        st.image(logo_path, width=128) 

with col2:
    st.markdown(f"""
        <h1 style='color: #8D203C; margin-bottom: 0; padding-top: 10px;'>Wave Optics Lab</h1>
        <p style='color: #002147; font-style: italic; font-size: 1.5em; margin-top: 0;'>
        College of the Ozarks | "Hard Work U"
        </p>
    """, unsafe_allow_html=True)

st.markdown(r"""
Welcome to the Wave Optics Lab! In this simulation, you will explore **Fraunhofer diffraction** and interference patterns generated by passing a laser through extremely narrow slits.

By adjusting the experimental parameters, you can observe how the wavelength ($\lambda$), slit width ($a$), and slit separation ($d$) govern the probability distribution of photons hitting the screen.
""")

# --- 2. Sidebar: Experimental Parameters ---
st.sidebar.header("1. Laser Settings")
mode = st.sidebar.radio("Configuration", ["Single Slit", "Double Slit"])
lam_nm = st.sidebar.slider("Wavelength [nm]", 400, 700, 633, step=1)
lam = lam_nm * 1e-9 

# Note: We use w_mm to control the visual 'fade' on the screen
w_mm = st.sidebar.slider("Visual Beam Spread [mm]", 10.0, 200.0, 100.0, step=10.0)
w = w_mm * 1e-3 

st.sidebar.header("2. Slit Geometry")
a_um = st.sidebar.slider("Slit Width (a) [μm]", 10, 200, 20, step=10)
a = a_um * 1e-6 

if mode == "Double Slit":
    d_um = st.sidebar.slider("Slit Separation (d) [μm]", 50, 500, 200, step=10)
    d = d_um * 1e-6
else:
    d = 0.0

st.sidebar.header("3. Environment")
L = st.sidebar.number_input("Distance to Screen (L) [m]", value=2.0, step=0.1)
exposure = st.sidebar.slider("Visual Exposure (Gain)", 0.01, 1.0, 0.2)

# --- 3. Physics & Math Logic ---
# Calculate the 'Zoom' based on physics: first null at L * lambda / a
y_null_mm = (L * lam / a) * 1000
zoom_limit = y_null_mm * (2.5 if mode == "Single Slit" else 1.5)
zoom_limit = max(min(zoom_limit, 200.0), 5.0) # Reasonable bounds

y_pts = np.linspace(-zoom_limit/1000, zoom_limit/1000, 3000)
theta = np.arctan(y_pts / L)

# Diffraction + Interference Math
beta = (a * np.sin(theta)) / lam
I_final = np.sinc(beta)**2

if mode == "Double Slit":
    alpha = (np.pi * d * np.sin(theta)) / lam
    I_final *= (np.cos(alpha)**2)

# The Gaussian 'fade' - We use a much wider W so it doesn't kill the fringes
I_final *= np.exp(-2 * (y_pts**2) / (w**2))

# --- 4. UI: Results & Metrics ---
st.subheader("Lab Analysis Results")
c1, c2, c3, c4 = st.columns(4)

c1.metric("Wavelength (λ)", f"{lam_nm} nm")

# Color Selection
laser_color = '#FF0000' if lam_nm >= 600 else '#00FF00' if lam_nm >= 495 else '#0000FF' if lam_nm >= 450 else '#8A2BE2'

if mode == "Double Slit":
    fringe_spacing = (lam * L / d) * 1000
    c2.metric("Fringe Spacing", f"{fringe_spacing:.2f} mm")
    c3.metric("m=1 Peak", f"±{fringe_spacing:.2f} mm")
    c4.metric("m=2 Peak", f"±{fringe_spacing*2:.2f} mm")
else:
    central_width = (2 * lam * L / a) * 1000
    first_side_peak = 1.43 * (lam * L / a) * 1000
    c2.metric("Central Max", f"{central_width:.1f} mm")
    c3.metric("1st Side Peak", f"±{first_side_peak:.1f} mm")
    c4.metric("Side Intensity", f"4.7%")

# --- 5. UI: Visualization ---
# Plot 1: Line Graph
fig1, ax1 = plt.subplots(figsize=(12, 3.5))
ax1.plot(y_pts * 1000, I_final, color=laser_color, lw=2)
ax1.fill_between(y_pts * 1000, I_final, color=laser_color, alpha=0.15)
ax1.set_xlim(-zoom_limit, zoom_limit)
ax1.set_ylim(0, 1.05)
ax1.set_xlabel("Screen Position (mm)")
ax1.set_ylabel("Relative Intensity")
st.pyplot(fig1)

# Plot 2: 2D Simulation
st.markdown("### Simulated Screen View")
y_vert = np.linspace(-3, 3, 100) 
X_grid, Y_grid = np.meshgrid(y_pts * 1000, y_vert)
vert_fade = np.exp(-2 * (Y_grid**2) / (1.5**2)) 
I_2d = I_final * vert_fade

from matplotlib.colors import LinearSegmentedColormap
laser_cmap = LinearSegmentedColormap.from_list("laser", [(0,0,0), laser_color])

fig2, ax2 = plt.subplots(figsize=(12, 1.2))
ax2.imshow(I_2d, extent=[-zoom_limit, zoom_limit, -3, 3], aspect='auto', cmap=laser_cmap, vmax=exposure)
ax2.axis('off')
st.pyplot(fig2)