import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import os

# --- 1. SETTINGS & BRANDING ---
# Official College of the Ozarks Branding
logo_path = "cofo-logo.jpg"

try:
    favicon = Image.open(logo_path)
    st.set_page_config(
        page_title="CofO | Wave Optics Lab", 
        page_icon=favicon, 
        layout="centered"
    )
except:
    st.set_page_config(
        page_title="CofO | Wave Optics Lab", 
        layout="centered"
    )

st.markdown("""
    <style>
        /* Target EVERYTHING inside the Sidebar and force it to White */
        section[data-testid="stSidebar"] * {
            color: white !important;
        }
        
        /* Fix the Input Boxes in the Sidebar so they are readable */
        section[data-testid="stSidebar"] input {
            color: #8D203C !important; 
        }

        /* Ensure the Main Area stays Black */
        .stApp p, .stApp h1, .stApp h2, .stApp h3, .stApp span {
            color: #000000;
        }
        
        /* Keep the Metric Labels Black */
        [data-testid="stMetricLabel"] {
            color: #444444 !important;
        }
        [data-testid="stMetricValue"] {
            color: #000000 !important;
        }

        /* Make the Sidebar Divider visible but subtle */
        section[data-testid="stSidebar"] hr {
            border-top: 1px solid #ffffff44 !important;
        }
    </style>
""", unsafe_allow_html=True)

if os.path.exists(logo_path):
    logo = Image.open(logo_path)
    st.sidebar.image(logo, use_container_width=True)
else:
    st.sidebar.warning(f"Logo '{logo_path}' not found in repo.")

# Sidebar Branding
st.sidebar.markdown("### **College of the Ozarks**\nDepartment of Mathematics and Physics")
st.sidebar.divider()

# --- Styled Main Header with Logo ---
col1, col2 = st.columns([1, 4]) 

with col1:
    if os.path.exists(logo_path):
        st.image(logo_path, width=128) 

with col2:
    st.markdown(f"""
        <h1 style='color: #8D203C; margin-bottom: 0; padding-top: 10px;'>Wave Optics Lab</h1>
        <p style='color: #002147; font-style: italic; font-size: 1.5em; margin-top: 0;'>
        College of the Ozarks | "Hard Work U"
        </p>
    """, unsafe_allow_html=True)

st.markdown(r"""
Welcome to the Wave Optics Lab! In this simulation, you will explore **Fraunhofer diffraction** and interference patterns generated by passing a laser through extremely narrow slits.

By adjusting the experimental parameters, you can observe how the wavelength ($\lambda$), slit width ($a$), and slit separation ($d$) govern the probability distribution of photons hitting the screen.
""")

# --- 2. Sidebar: Experimental Parameters ---
st.sidebar.header("1. Laser Settings")
mode = st.sidebar.radio("Configuration", ["Single Slit", "Double Slit"])
lam_nm = st.sidebar.slider("Wavelength [nm]", 400, 700, 633, step=1)
lam = lam_nm * 1e-9  # Convert to meters

# Gaussian Beam profile
w_mm = st.sidebar.slider("Laser Beam Spread [mm]", 1.0, 20.0, 5.0, step=0.5)
w = w_mm * 1e-3  # Convert to meters

st.sidebar.header("2. Slit Geometry")
a_um = st.sidebar.slider("Slit Width (a) [μm]", 10, 200, 50, step=10)
a = a_um * 1e-6  # Convert to meters

if mode == "Double Slit":
    d_um = st.sidebar.slider("Slit Separation (d) [μm]", 50, 500, 250, step=10)
    d = d_um * 1e-6
else:
    d = 0.0

st.sidebar.header("3. Environment")
L = st.sidebar.number_input("Distance to Screen (L) [m]", value=2.0, step=0.1)

# --- 3. Physics & Math Functions ---
# Generate spatial array (y) from -50mm to +50mm
y = np.linspace(-0.05, 0.05, 2000)
theta = np.arctan(y / L)

# Single slit diffraction envelope
# np.sinc(x) calculates sin(pi*x)/(pi*x). We define x = (a*sin(theta))/lam
beta_norm = (a * np.sin(theta)) / lam
I_single = np.sinc(beta_norm)**2

# Double slit interference pattern
if mode == "Double Slit":
    alpha = (np.pi * d * np.sin(theta)) / lam
    I_interfere = np.cos(alpha)**2
    I_ideal = I_single * I_interfere
else:
    I_ideal = I_single

# Apply Gaussian laser beam envelope
I_gaussian = np.exp(-2 * (y**2) / (w**2))
I_final = I_ideal * I_gaussian

# --- 4. UI: Results & Metrics ---
st.subheader("Lab Analysis Results")

c1, c2, c3, c4 = st.columns(4)
c1.metric("Wavelength (λ)", f"{lam_nm} nm")

# Determine realistic laser color for plot
if lam_nm >= 600:
    laser_color = '#FF0000' # Red
elif lam_nm >= 495:
    laser_color = '#00FF00' # Green
elif lam_nm >= 450:
    laser_color = '#0000FF' # Blue
else:
    laser_color = '#8A2BE2' # Violet

if mode == "Double Slit":
    fringe_spacing_mm = (lam * L / d) * 1000
    c2.metric("Predicted Spacing (Δy)", f"{fringe_spacing_mm:.3f} mm")
    
    # Calculate maxima locations for m=1 and m=2
    m1_mm = (1 * lam * L / d) * 1000
    m2_mm = (2 * lam * L / d) * 1000
    c3.metric("m=1 Maximum (±)", f"{m1_mm:.3f} mm")
    c4.metric("m=2 Maximum (±)", f"{m2_mm:.3f} mm")
else:
    central_max_width = (2 * lam * L / a) * 1000
    c2.metric("Central Max Width", f"{central_max_width:.3f} mm")
    m1_min_mm = (1 * lam * L / a) * 1000
    c3.metric("1st Minimum (±)", f"{m1_min_mm:.3f} mm")
    c4.metric("Configuration", "Single Slit")

with st.expander("📊 Mathematical Model Details"):
    st.markdown("""
    The intensity distribution $I(\\theta)$ combines Fraunhofer diffraction, interference, and a realistic Gaussian beam profile.
    
    * **Diffraction Envelope:** $I_{single} = \\left(\\frac{\\sin \\beta}{\\beta}\\right)^2$
    * **Interference Term (Double Slit):** $I_{double} = I_{single} \\cdot \\cos^2 \\alpha$
    * **Gaussian Beam Factor:** Accounts for the laser intensity tapering off from the center: $\\exp\\left(-\\frac{2y^2}{w^2}\\right)$
    
    Where $\\beta = \\frac{\\pi a \\sin \\theta}{\\lambda}$ and $\\alpha = \\frac{\\pi d \\sin \\theta}{\\lambda}$. Note that as per standard probability models in quantum mechanics, this intensity graph represents the *probability distribution* of where an individual photon will land.
    """)

# --- 5. UI: Visualization ---
try:
    # Set up a clean, professional plot without unnecessary gridlines or backgrounds
    fig, ax = plt.subplots(figsize=(12, 5))
    
    # Plot final intensity
    ax.plot(y * 1000, I_final, color=laser_color, lw=2.5, label='Measured Intensity')
    ax.fill_between(y * 1000, I_final, color=laser_color, alpha=0.3)
    
    # Optional: Plot the single slit envelope to show how it bounds the double slit pattern
    if mode == "Double Slit":
        ax.plot(y * 1000, I_single * I_gaussian, color='gray', linestyle='--', lw=1.5, alpha=0.8, label='Diffraction Envelope')

    # Formatting for a clean manual aesthetic
    ax.set_xlim(-50, 50)
    ax.set_ylim(0, 1.05)
    ax.set_xlabel("Position on Screen, y (mm)", fontsize=12)
    ax.set_ylabel("Relative Intensity", fontsize=12)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.legend(loc='upper right', frameon=False)
    
    st.pyplot(fig)
    
    # --- 2D Laser Simulation (Add this below your line graph code) ---
    st.markdown("### Simulated Screen View")
    
    # Create a vertical grid to simulate the height of the laser dot
    # We use a vertical Gaussian profile to make it look like a real beam
    y_vertical = np.linspace(-5, 5, 200) # +/- 5mm vertical spread
    X_grid, Y_grid = np.meshgrid(y * 1000, y_vertical)
    
    # Apply a vertical Gaussian decay (assuming a 2mm vertical beam radius)
    vertical_profile = np.exp(-2 * (Y_grid**2) / (2.0**2))
    
    # The 2D image is the 1D horizontal intensity multiplied by the vertical profile
    I_2d_image = I_final * vertical_profile
    
    # Create a custom colormap that fades to black instead of white
    from matplotlib.colors import LinearSegmentedColormap
    colors = [(0, 0, 0), laser_color] # Fade from black to the laser color
    laser_cmap = LinearSegmentedColormap.from_list("custom_laser", colors)

    fig2, ax2 = plt.subplots(figsize=(12, 2))
    
    # Plot the 2D image
    img = ax2.imshow(I_2d_image, extent=[-50, 50, -5, 5], aspect='auto', 
                     cmap=laser_cmap, origin='lower', vmax=1.0)
    
    # Clean up the axes to look like a dark room
    ax2.set_facecolor('black')
    ax2.set_xlabel("Position on Screen, y (mm)", fontsize=12)
    ax2.set_yticks([]) # Hide vertical axis ticks for a cleaner look
    
    st.pyplot(fig2)

except Exception as e:
    st.error(f"Visualization Error: {e}")